import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const DEMO_EMAIL = 'demo@devinterview.ai';
const DEMO_PASSWORD = 'demo1234'; // seed-only account, intentionally simple — never used in production

/**
 * Seeds a demo user with realistic-looking history so a recruiter (or you,
 * showing this off) can explore the dashboard/report/history pages
 * immediately without configuring or running a real interview first.
 * Everything here is static fixture data, not generated by an AI
 * provider — this script runs with no API key and no network calls.
 */
async function main() {
  console.log('Seeding demo user...');

  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);

  const user = await prisma.user.upsert({
    where: { email: DEMO_EMAIL },
    update: {},
    create: {
      email: DEMO_EMAIL,
      name: 'Demo Candidate',
      passwordHash,
      profile: {
        create: {
          targetRole: 'FULL_STACK_DEVELOPER',
          experienceLevel: 'ONE_TO_THREE_YEARS',
          primarySkills: ['JavaScript', 'React', 'Node.js', 'SQL']
        }
      }
    }
  });

  // --- Interview 1: fully evaluated, with a detailed report (the one the demo links to) ---
  const interview1 = await prisma.interview.create({
    data: {
      userId: user.id,
      targetRole: 'FULL_STACK_DEVELOPER',
      experienceLevel: 'ONE_TO_THREE_YEARS',
      skills: ['JavaScript', 'React', 'Node.js', 'SQL', 'System Design'],
      durationMinutes: 30,
      state: 'EVALUATED',
      startedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      completedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000 + 28 * 60 * 1000)
    }
  });

  await prisma.interviewPlan.create({
    data: {
      interviewId: interview1.id,
      sections: [
        { type: 'introduction', duration: 3 },
        { type: 'javascript', duration: 6 },
        { type: 'react', duration: 7 },
        { type: 'system_design', duration: 10 },
        { type: 'candidate_questions', duration: 4 }
      ]
    }
  });

  const q1 = await prisma.interviewQuestion.create({
    data: {
      interviewId: interview1.id,
      sequence: 1,
      section: 'javascript',
      type: 'CONCEPTUAL',
      prompt: 'What is the difference between `useEffect` and `useLayoutEffect` in React?',
      difficulty: 3
    }
  });
  const a1 = await prisma.candidateAnswer.create({
    data: {
      questionId: q1.id,
      content:
        'useEffect runs asynchronously after the browser paints, while useLayoutEffect runs synchronously before paint. I\'d use useLayoutEffect when I need to measure the DOM and make changes before the user sees anything, like preventing a flicker.'
    }
  });
  await prisma.answerEvaluation.create({
    data: {
      answerId: a1.id,
      technicalAccuracy: 9,
      problemSolving: 7,
      communication: 8,
      depthOfUnderstanding: 8,
      coveredConcepts: ['paint timing', 'synchronous vs asynchronous effects', 'DOM measurement use case'],
      missedConcepts: ['server-side rendering implications'],
      explanation: 'Strong, precise answer that correctly identifies the paint-timing distinction and gives a concrete, appropriate use case.',
      suggestedAnswer: 'Also worth mentioning: useLayoutEffect has no effect during server-side rendering and can trigger a console warning if used there without a client-only guard.'
    }
  });

  const q2 = await prisma.interviewQuestion.create({
    data: {
      interviewId: interview1.id,
      sequence: 2,
      section: 'system_design',
      type: 'CONCEPTUAL',
      prompt: 'How would you design a rate limiter for a public API?',
      difficulty: 3
    }
  });
  const a2 = await prisma.candidateAnswer.create({
    data: {
      questionId: q2.id,
      content:
        'I would use a token bucket approach with Redis to track request counts per API key, with a sliding window.'
    }
  });
  await prisma.answerEvaluation.create({
    data: {
      answerId: a2.id,
      technicalAccuracy: 5,
      problemSolving: 5,
      communication: 6,
      depthOfUnderstanding: 4,
      coveredConcepts: ['token bucket algorithm', 'per-key limiting'],
      missedConcepts: ['distributed consistency across Redis nodes', 'handling burst traffic', 'what happens when the limit is exceeded (429 response, retry-after headers)'],
      explanation: 'Correctly named a reasonable algorithm and storage choice, but the answer stayed at a high level and did not engage with distributed-systems edge cases when pressed.',
      suggestedAnswer: 'A stronger answer would discuss what happens under Redis failover, how to keep counts consistent across replicas, and the actual client-facing behavior (status code, headers) when a client is throttled.'
    }
  });

  const report1 = await prisma.interviewReport.create({
    data: {
      interviewId: interview1.id,
      overallScore: 74,
      technicalKnowledge: 78,
      problemSolving: 65,
      coding: 70,
      communication: 80,
      depthOfUnderstanding: 68,
      roleFit: 75,
      strengths: [
        'Clearly explained React rendering/effect timing with a correct, specific use case',
        'Communicated technical ideas in a structured, easy-to-follow way throughout'
      ],
      weaknesses: [
        'Rate limiter design stayed conceptual — did not address distributed consistency or failure modes when pressed',
        'Limited depth on database indexing trade-offs'
      ],
      evidence: [
        {
          topic: 'React Effects',
          score: 9,
          narrative:
            'Correctly distinguished useEffect from useLayoutEffect by paint timing and gave a precise DOM-measurement use case without prompting.'
        },
        {
          topic: 'System Design',
          score: 5,
          narrative:
            'Named token bucket + Redis for a rate limiter but could not extend the design to cover node failover or burst-handling when asked a follow-up.'
        }
      ],
      studyPlan: [
        {
          priority: 1,
          title: 'Distributed system failure modes',
          why: 'The rate limiter answer did not hold up under a follow-up about Redis failover or multi-node consistency.',
          practice: [
            'Read about the CAP theorem trade-offs in rate limiter design specifically',
            'Practice explaining what happens to a system when its shared state store becomes unavailable'
          ]
        }
      ]
    }
  });

  await prisma.skillScore.createMany({
    data: [
      { userId: user.id, interviewId: interview1.id, topic: 'React Effects', score: 90 },
      { userId: user.id, interviewId: interview1.id, topic: 'System Design', score: 50 }
    ]
  });

  // --- Interview 2 & 3: lighter-weight completed interviews for dashboard trend/history ---
  for (const [offsetDays, score, role] of [
    [3, 81, 'FRONTEND_DEVELOPER'],
    [1, 69, 'BACKEND_DEVELOPER']
  ]) {
    const interview = await prisma.interview.create({
      data: {
        userId: user.id,
        targetRole: role,
        experienceLevel: 'ONE_TO_THREE_YEARS',
        skills: ['JavaScript', 'TypeScript', 'REST APIs'],
        durationMinutes: 15,
        state: 'EVALUATED',
        startedAt: new Date(Date.now() - offsetDays * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - offsetDays * 24 * 60 * 60 * 1000 + 14 * 60 * 1000)
      }
    });
    await prisma.interviewReport.create({
      data: {
        interviewId: interview.id,
        overallScore: score,
        technicalKnowledge: score,
        problemSolving: score - 5,
        coding: score,
        communication: score + 5 > 100 ? 100 : score + 5,
        depthOfUnderstanding: score - 8,
        roleFit: score,
        strengths: ['Solid grasp of core JavaScript fundamentals'],
        weaknesses: ['Could go deeper on asynchronous error handling patterns'],
        evidence: [{ topic: 'JavaScript', score: Math.round(score / 10), narrative: 'Demo data — see interview1 for a fully worked example.' }],
        studyPlan: [{ priority: 1, title: 'Async error handling', why: 'Demo data.', practice: ['Review Promise.allSettled vs Promise.all failure semantics'] }]
      }
    });
    await prisma.skillScore.create({
      data: { userId: user.id, interviewId: interview.id, topic: 'JavaScript', score }
    });
  }

  // --- One coding challenge + submission on interview 1, for the "one coding challenge result" requirement ---
  const codingQuestion = await prisma.interviewQuestion.create({
    data: {
      interviewId: interview1.id,
      sequence: 3,
      section: 'coding',
      type: 'CODING',
      prompt: 'First Non-Repeating Character',
      difficulty: 3
    }
  });
  const codingChallenge = await prisma.codingChallenge.create({
    data: {
      interviewId: interview1.id,
      questionId: codingQuestion.id,
      title: 'First Non-Repeating Character',
      statement: 'Implement a function that returns the first non-repeating character in a string, or an empty string if none exists.',
      constraints: '1 <= s.length <= 10^5',
      examples: [{ input: '"leetcode"', output: '"l"' }],
      starterCode: { javascript: 'function firstNonRepeating(s) {\n  // your code here\n}' },
      visibleTests: [
        { input: '"leetcode"', expectedOutput: 'l' },
        { input: '"aabb"', expectedOutput: '' }
      ],
      hiddenTests: [
        { input: '""', expectedOutput: '' },
        { input: '"a"', expectedOutput: 'a' }
      ]
    }
  });
  await prisma.codeSubmission.create({
    data: {
      codingChallengeId: codingChallenge.id,
      language: 'javascript',
      code: `function firstNonRepeating(s) {
  const counts = {};
  for (const ch of s) counts[ch] = (counts[ch] || 0) + 1;
  for (const ch of s) if (counts[ch] === 1) return ch;
  return '';
}`,
      passedVisible: 2,
      totalVisible: 2,
      passedHidden: 2,
      totalHidden: 2,
      aiReview: {
        correctness: 10,
        time_complexity: 'O(n)',
        space_complexity: 'O(n)',
        readability: 9,
        edge_case_handling: 'Correctly handles empty string and single-character input via the counts map.'
      }
    }
  });

  console.log(`Seeded demo user: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
  console.log(`  - 3 completed interviews, 1 with a full detailed report + coding submission`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
